### PR TITLE
max number from a list and Factorial #2 and #7

### PR DESCRIPTION
**Pull request by iriyagupta**
This is the pull request for the issues #7 and the factorial issue #2

### CODE REVIEW

**Comment by pranav2012** [comment]
ok we'll merge after 1st October when the fest will begin 
link pull request to the issue just edit your description and write #7

**Comment by iriyagupta** [comment]
@pranav2012  Hi does this suffice?

**Comment by pranav2012** [comment]
Yes, Absolutely Happy Coding!!

**Comment by iriyagupta** [comment]
I will slightly modify the code with some comments. I hope that works

**Comment by pranav2012** [comment]
Sure just add a comment on the issue so that I can assign you

**Comment by iriyagupta** [comment]
Added the description and have pulled the request

**Comment by pranav2012** [comment]
Great:+1:

**Pull request merged**
