### PR TITLE
Reverse String Program

### PR DESCRIPTION
**Pull request by rishavjaiss**
Hi, 
This is my first contribution to open source. Please merge this on 1st October.
Thanks.

### CODE REVIEW

**Comment by rishavjaiss** [comment]
Hey,
Please review this pr and merge it. Thanks!

**Comment by rishavjaiss** [comment]
Hey even after successful merge my pr count in hacktoberfest didn't go up. Why?

**Comment by pranav2012** [comment]
What they are saying??

**Comment by rishavjaiss** [comment]
we need to make pr from today only. Before today will not be counted even if it's merged.

**Comment by pranav2012** [comment]
Do one thing just slightly change the code add comments nd make another pull request

**Pull request merged**
